package me.santipingui58.splindux.stats;

public enum RankingType {
	SPLEEF1VS1_WINS,
	SPLEEF1VS1_GAMES,
	SPLEEF1VS1_ELO,
	SPLEEF1VS1_WINS_MONTHLY,
	SPLEEF1VS1_WINS_WEEKLY,
	SPLEEF1VS1_GAMES_MONTHLY,
	SPLEEF1VS1_GAMES_WEEKLY,
	SPLEEFFFA_WINS,
	SPLEEFFFA_GAMES,
	SPLEEFFFA_KILLS,
	SPLEEFFFA_WINS_MONTHLY,
	SPLEEFFFA_WINS_WEEKLY,
	SPLEEFFFA_GAMES_MONTHLY,
	SPLEEFFFA_GAMES_WEEKLY,
	SPLEEFFFAA_KILLS_MONTHLY,
	SPLEFFFA_KILLS_WEEKLY,
	SPLEEFFFA_KG,
	SPLEEFFFA_WG;
}
